---
AWSTemplateFormatVersion: '2010-09-09'

#Parameters:

#Mappings:

Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: NeverValid

#Outputs:
