---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Name:
    Type: String
    Default: hello
    Description: a description
    
#Mappings:


Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: NeverValid

# lets add a comment
#Outputs:
