---
AWSTemplateFormatVersion: '2010-09-09'
Description: Misc

Parameters:
  Name:
    Type: String
    Default: hello
    Description: changed
  
  Host:
    Type: String
    Default: name

Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullRsource'
    Condition: NeverValid
    Description: a valid description would go here
