---
AWSTemplateFormatVersion: '2010-09-09'
Description: a new version of this file

Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullRsource'
    Condition: NeverValid
