---
AWSTemplateFormatVersion: '2010-09-09'
Description: Misc words an ipsum facto

Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: NeverValid
