---
AWSTemplateFormatVersion: '2010-09-09'
Description: Misc words an ipsum facto

Parameters:
  Name:
    Type: String
    Default: hello
    Description: changed
  
  Host:
    Type: String
    Default: name

Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: NeverValid
