---
AWSTemplateFormatVersion: '2010-09-09'
Description: Misc

Parameters:
  Test:
    Description: test description
    Type: String
    Default: jim
    
Conditions:
  NeverValid: !Equals [ True, False ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: NeverValid
